server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  application:
      name: redis-manager
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  datasource:
      name: serverbase
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.16.46.170:3306/redis_manager_new?useUnicode=true&characterEncoding=utf-8
      username: test
      password: test

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
      mapUnderscoreToCamelCase: true

cache:
    user.api.path: D:/work/java/cache-platform/redis-manager/src/main/resources/public/core/userApi.js
    mysql.scan.package: com.newegg.ec.cache
    humpback.image: humpback-hub.newegg.org/shec/redis3.0.6:v3,docker.neg/shec/redis-4.0.8:v1